- hosts: localhost
  vars:
   host: 192.168.159.112
   username: "admin"
   password: "admin"
   vdom: "root"
  tasks:
  - name: Configure interface port1.
    fortios_system_interface:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      system_interface:
        state: "present"
        name: "port1"
        mode: "dhcp"
        allowaccess:
          - ping
          - ssh
          - https
          - fgfm
          - http
  - name: Configure interface port2.
    fortios_system_interface:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      system_interface:
        state: "present"
        name: "port2"
        mode: "dhcp"
        allowaccess:
          - ping
          - ssh
          - https
          - fgfm
          - http
  - name: Configure interface port3.
    fortios_system_interface:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      system_interface:
        state: "present"
        name: "port3"
        mode: "dhcp"
        allowaccess:
          - ping
          - ssh
          - https
          - fgfm
          - http
  - name: Configure IPsec manual keys.
    fortios_vpn_ipsec_manualkey_interface:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      vpn_ipsec_manualkey_interface:
        state: "present"
        auth_alg: "null" 
        enc_key: "{{ enc_key }}"
        enc_alg: "{{ enc_alg }}"
        interface: "port2"
        local_gw: "{{ local_gw }}"
        local_spi: "{{ local_spi }}"
        name: "{{ tunnel_name }}"
        remote_gw: "{{ remote_gw }}"
        remote_spi: "{{ remote_spi }}"
  - name: Configure IPv4 policy1.
    fortios_firewall_policy:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      firewall_policy:
        state: "present"
        policyid: "1"
        name: "policy1"
        action: "accept"
        srcintf: [ {"name": "port3"} ]
        dstintf: [{"name":"port2"} ]
        srcaddr: [{"name":"all"} ]
        dstaddr: [{"name":"all"}]
        schedule: "always"
        service: [{"name":"ALL"}]
        logtraffic: "all"
  - name: Configure IPv4 policy2.
    fortios_firewall_policy:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      firewall_policy:
        state: "present"
        policyid: "2"
        name: "policy2"
        action: "accept"
        srcintf: [ {"name": "port3"} ]
        dstintf: [{"name":"{{ tunnel_name }}"} ]
        srcaddr: [{"name":"all"} ]
        dstaddr: [{"name":"all"}]
        schedule: "always"
        service: [{"name":"ALL"}]
        logtraffic: "all"
  - name: Configure IPv4 policy3.
    fortios_firewall_policy:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      firewall_policy:
        state: "present"
        policyid: "3"
        name: "policy3"
        action: "accept"
        srcintf: [ {"name": "{{ tunnel_name }}"} ]
        dstintf: [{"name":"port3"} ]
        srcaddr: [{"name":"all"} ]
        dstaddr: [{"name":"all"}]
        schedule: "always"
        service: [{"name":"ALL"}]
        logtraffic: "all"
  - name: Configure IPv4 static routing tables.
    fortios_router_static:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "False"
      router_static:
        state: "present"
        dst: "{{ remote_internal }}"
        device: "{{ tunnel_name }}"
        seq_num: "1"



